# Generated by Django 5.0 on 2023-12-23 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblBanco',
            fields=[
                ('co_cod_banco', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('co_ispb_banco', models.CharField(blank=True, max_length=8)),
                ('de_nome_banco', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TblChavePix',
            fields=[
                ('co_chave_pix', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('co_nome_titular', models.CharField(blank=True, max_length=100)),
                ('co_numero_conta', models.CharField(blank=True, max_length=45)),
                ('co_cod_banco', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TblResponse',
            fields=[
                ('bc_endtoendid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bc_ts_request', models.DateTimeField(auto_now=True)),
                ('bc_banco_pagador', models.CharField(max_length=4)),
                ('bc_conta_pagador', models.CharField(max_length=45)),
                ('bc_info_pagador', models.CharField(max_length=255)),
                ('bc_chave_pix', models.CharField(max_length=100)),
                ('bc_nome_titular', models.CharField(blank=True, max_length=100)),
                ('bc_numero_conta', models.CharField(blank=True, max_length=45)),
                ('bc_cod_banco', models.CharField(max_length=4)),
                ('bc_valor', models.DecimalField(decimal_places=2, default=1.0, max_digits=22)),
                ('bc_status_request', models.CharField(max_length=25)),
            ],
        ),
    ]
